/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.popover;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="TiPopover", id="ti.popover")
public class TiPopoverModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TiPopoverModule";
	private static final boolean DBG = TiConfig.LOGD;

	@Kroll.constant public static final int POPOVER_ARROW_DIRECTION_ANY = 0;
	@Kroll.constant public static final int POPOVER_ARROW_DIRECTION_DOWN = 1;
	@Kroll.constant public static final int POPOVER_ARROW_DIRECTION_UP = 2;
	@Kroll.constant public static final int POPOVER_ARROW_DIRECTION_LEFT = 3;
	@Kroll.constant public static final int POPOVER_ARROW_DIRECTION_RIGHT = 4;

	@Kroll.constant public static final int POPOVER_ANIMATION_NONE = 0;
	@Kroll.constant public static final int POPOVER_ANIMATION_FADE = 1;
	@Kroll.constant public static final int POPOVER_ANIMATION_OVERSHOOT = 2;
	@Kroll.constant public static final int POPOVER_ANIMATION_ELASTIC = 3;
	@Kroll.constant public static final int POPOVER_ANIMATION_CIRCULAR = 4;

	public TiPopoverModule()
	{
		super();
	}


}

